# Generated by Django 5.2 on 2025-09-01 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_groupassetpurchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
