# Generated by Django 5.2 on 2025-09-16 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_alter_membership_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walletasset',
            name='quantity',
            field=models.DecimalField(decimal_places=5, max_digits=10),
        ),
    ]
