# Generated by Django 5.2 on 2025-09-22 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_alter_walletasset_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='walletasset',
            name='currency',
            field=models.CharField(choices=[('USD', 'USD'), ('EUR', 'EUR'), ('GBP', 'GBP'), ('JPY', 'JPY'), ('CAD', 'CAD')], default='USD', max_length=3),
        ),
    ]
