# Generated by Django 5.2 on 2025-09-22 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_walletasset_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walletasset',
            name='currency',
        ),
    ]
