# Generated by Django 5.2 on 2025-09-22 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_remove_walletasset_currency'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssetTrend',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=10)),
                ('timeframe', models.CharField(max_length=10)),
                ('change_pct', models.DecimalField(decimal_places=2, max_digits=10)),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('symbol', 'timeframe')},
            },
        ),
    ]
