# Generated by Django 5.2 on 2025-09-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_assettrend'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='group',
            name='purchase_period_days',
            field=models.PositiveIntegerField(default=7),
        ),
        migrations.AddField(
            model_name='group',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
