# Generated by Django 5.2 on 2025-09-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_group_end_time_group_purchase_period_days_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='group',
            old_name='purchase_period_days',
            new_name='purchase_days',
        ),
        migrations.RenameField(
            model_name='group',
            old_name='end_time',
            new_name='purchase_end_time',
        ),
        migrations.AddField(
            model_name='group',
            name='summary_days',
            field=models.PositiveIntegerField(default=14),
        ),
        migrations.AddField(
            model_name='group',
            name='summary_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
