from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views
from core import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('api/login/', views.api_login, name='api_login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('register/', views.register, name='register'),
    path('api/register/', views.api_register, name='api_register'),
    path('', views.home, name='home'),
    path('accounts/profile/', views.profile, name='profile'),
    path('accounts/profile/wallets/', views.wallets, name='wallet_list'),
    path('api/accounts/profile/wallets/<int:user_id>/', views.api_wallets, name='api_wallet_list'),
    path('accounts/profile/wallets/add_wallet/', views.add_wallet, name='add_wallet'),
    path('api/accounts/profile/wallets/add_wallet/', views.api_add_wallet, name='api_add_wallet'),
    path('accounts/profile/wallets/<int:wallet_id>/', views.wallet_detail, name='wallet_detail'),
    path('accounts/profile/wallets/<int:wallet_id>/<int:asset_id>/', views.wallet_asset_detail, name='wallet_asset_detail'),
    path('api/accounts/profile/wallets/<int:wallet_id>/<int:asset_id>/', views.api_wallet_asset_detail, name='api_wallet_asset_detail'),
    path('api/accounts/profile/wallets/wallet/<int:wallet_id>/', views.api_wallet_detail, name='api_wallet_detail'),
    path('accounts/profile/wallets/<int:wallet_id>/add_wallet_asset/', views.add_wallet_asset, name='add_wallet_asset'),
    path('api/assets/', views.api_list_of_assets, name='api_list_of_assets'),
    path('account/profile/wallets/<int:wallet_id>/add_wallet_asset/<int:asset_id>/', views.add_wallet_asset_details, name='add_wallet_asset_details'),
    path('api/account/profile/wallets/<int:wallet_id>/add_wallet_asset/<int:asset_id>/', views.api_add_wallet_asset_details, name='api_add_wallet_asset_details'),
    path('accounts/profile/wallets/remove_wallet/<int:wallet_id>/', views.remove_wallet, name='remove_wallet'),
    path('api/accounts/profile/wallets/remove_wallet/<int:wallet_id>/', views.api_remove_wallet, name='api_remove_wallet'),
    path('price/', views.price, name='price'),
    path('api/price/', views.api_price, name='api_price'),
    path('assets/', views.asset_list, name='asset_list'),
    path('api/asset/<str:symbol>/price/', views.api_asset_price, name='api_asset_price'),
    path('asset/<str:symbol>/history/', views.asset_history, name='historic_price'),
    path('api/asset/<str:symbol>/history/', views.api_asset_history, name='api_history_price'),
    path('api/asset/<str:symbol>/history/<str:day>/', views.api_asset_history_filter, name='api_history_price_filter'),
    path('trends/', views.trends, name='trends'),
    path('friends/', views.friends_list, name='friends_list'),
    path('api/friends/', views.api_friends_list, name='api_friends_list'),
    path('friends/send-request/<int:user_id>/', views.send_friend_request, name='send_friend_request'),
    path('friends/accept-request/<int:request_id>/', views.accept_friend_request, name='accept_friend_request'),
    path('friends/decline-request/<int:request_id>/', views.decline_friend_request, name='decline_friend_request'),
    path('friends/remove-friend/<int:user_id>/', views.remove_friend, name='remove_friend'),
    path('goals/', views.user_goals, name='user_goals'),
    path('goals/add/', views.add_user_goal, name='add_user_goal'),
    path('my_alerts', views.my_alerts, name = 'my_alerts'),
    path('goals/delete/<int:goal_id>/', views.delete_user_goal, name='delete_user_goal'),
    path('assets/<int:asset_id>/add-alert/', views.add_price_alert, name='add_price_alert'),
    path('api/asset/name/<str:symbol>/', views.api_asset_name, name='api_asset_name'),
    path('wallet/<int:wallet_id>/asset/<int:asset_id>/remove/', views.remove_wallet_asset, name='remove_wallet_asset'),
    path('wallet/<int:wallet_id>/asset/<int:asset_id>/transaction/<int:transaction_id>/delete/',views.delete_wallet_transaction,name='delete_wallet_transaction'),
    path('api/wallet/<int:wallet_id>/asset/<int:asset_id>/remove/', views.api_remove_wallet_asset, name='api_remove_wallet_asset'),
    path('api/wallet/<int:wallet_id>/asset/<int:asset_id>/transaction/<int:transaction_id>/delete/',views.api_delete_wallet_transaction,name='api_delete_wallet_transaction'),
    path('wallet/<int:wallet_id>/share/', views.share_wallet, name='share_wallet'),
    path('shared-wallets/', views.shared_wallets, name='shared_wallets'),
    path('shared-wallet/<int:wallet_id>/', views.shared_wallet_detail, name='shared_wallet_detail'),





]
